name: CI

on:
  push:
  pull_request:

env:
  GO111MODULE: 'on'

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - name: Install project dependencies
      run: go get
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
    - name: Use go-deadlock
      run: ./tests/use-go-deadlock.sh
    - name: Test
      run: go test -race -covermode atomic -coverprofile=profile.cov ./...
    - name: Upload coverage results
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
